### PR TITLE
Gpapa dev

### PR DESCRIPTION
**Pull request by Joe-Joe-Joe-Joe**
- Addressed Jack's preliminary comments
- ERC warnings remain

### CODE REVIEW

**Comment by rdakhil** [comment]
I think the shutdown is configured incorrectly on the 4.5V buck regulator. It is active low, meaning that when it is pulled low, the device will be in shutdown. it should be either floating, or pulled high by default (ideally) then pulled low by the MCU when we want the device to shut down. In this configuration, the regulator will default to being off then will only turn on when the MCU is pulling it high. Not ideal as the system will never be able to turn on unless we connect the batteries first.
image

**Comment by rdakhil** [comment]
Good job on cleaning up the schematic, looks a lot better and less confusing than before! I will quickly fix the shutdown pin issue.

**Review by BluCodeGH — DISMISSED** [review]
Comments from the streamed review:

1. Your canhw library points to `canhw/lib/canhw.kicad_sym` which isn't a file that exists (at least not in the canhw git). You mean to point at `canhw.lib`.
2. It would be good to have a text comment somewhere explaining the whole powerpath since its sorta split up atm.
3. Your mcp2652 and 2515 wiring could be a lot cleaner (and overall stuff could be more spaced out). Especially with the 2562 why are there two 5V symbols _right_ next to each other? See USB debug for a pretty wiring for the 2515.
4. Your 12->5 regulator can only do 1.25A so your 5V boost regulator shouldn't be designed for 2A. Check the 2022 irec final report for current draw numbers but I'd guess the total system power draw will be on the order of 300 mA.
5. Right now you have current sensing on both the 5V boost output and after the aux power switch. The post-power-switch sense is pretty redundant, imo it would be more useful between the rocketcan 12v line and the 12->5 buck so we can see how much / whether we are drawing any power from the rocket.
6. your 12->buck circuit is missing a junction between D1 and L1. See kids this is why we don't join 4 wires at one point.
7. I'd recommend hooking the charger status pins up to the pic so we can report the status over CAN. Likewise battery voltage sensing is important to have.

**Comment by Joe-Joe-Joe-Joe** [comment]
It is going to take ages to fix grid spacing - I don't think its worth it tbh

**Review by LanaTomlin — CHANGES_REQUESTED** [review]
okay, fair wrning, my computer 'a' key is stuck so it may be ommitted in lots of plces, sorry. 

1. in J2 we should mark canl and canh on the connector istelf for  better visabiliy
2. really love that connector types are marked, but gnd pins are missing connector type
3. overall layout and readability is 10/10 so good ahhhhhhhhhh
4. on the previous papa board, the 150ohm resistors were very bright, might be worth consiering increasing that vlue a bit
5. possibly worth considering breaking out rb5 to a test point/dupont pin in case we wanna use it for something
6. MCP2562 datasheet seems to reccomend 0.1uF decoupling caps not 10uF
7. p55 or MCP2515 datasheet seems to reccomend a pull down resistor on osc2 to reduce noise
8. should double check oscillator timign characteristics pg 75 of MCP2515 datasheeet
9. where does 4.5V come from SEE THE NOTE NOW I GET ti looks good
10. for MCP73871T-1CCI/ML what diff betrweeen ac/dc dapter and usb charging modes
11. bit confused about TE on charging circuit i think its fine though uhhh idk 
12. is LT1576IS8-5#TRPBF availble in single units? all i cn see is 2.5k min 
13. LT1576IS8-5#TRPBF datasheet specifies c6 be solid tantanium 
14. might be easier to get 33uH inductor do we have specifications on which part this is
15. what voltage are we putting on LT1576IS8-5#TRPBF SYNC pin its max is 7V
16. c3 is disconnected
17. gnd on LT1576IS8-5#TRPBF also disconnected 
18. would apprecite a bit of more of explntion of the 12V pwr disable stuff not sure what r16 and r25 are doing
19. TPS61023DRLT out of stock 
20. why is l2 2uH, datasheet is saying 1uH


OAKY I THINK THATS ALL I GOT FOR NOW PEACE YALL 
thank u for your time, and servicef

will look at pcb later

**Comment by Joe-Joe-Joe-Joe** [comment]
1 - Disagree. The pins are sitting right below it, i think its clear which is which and this keeps the main sheet clean.
2/4/5/7 done
6 - every other board I've looked at uses 10uF. The TCAN1042 also recommends 0.1 uF decoupling. Will clarify
8 - frequency and voltage are within spec, not sure if there's anything else to check?
10 - ac/dc mode limits charge current to a flat 1.65A, USB mode expects you to be connected to a USB cable for power and follow the USB spec for current which we nothing to do with in this case
11 - we didn't really know what to make of it either - that's why its always pulled high lol
12-20 - working on replacement ICs as we speak ;-;

**Comment by Joe-Joe-Joe-Joe** [comment]
TODO
- [x] 5v boost reg symbol should not incl pin 9 (thermal pad); MSOP-8 footprint is correct
- [ ] Merge all Papa symbols and footprints into single "grandpapa" library
- [ ] Replace all test points with Artem's fancy new test points from minisensor
- [ ] Consider making TH1 a through-hole component (may have to run leads to put in contact w lipo)

**Review by LanaTomlin — DISMISSED** [review]
1. we had some issues with debuging/testing when on papa when the 5V on Harwin connector was disconnected, might wanna connect the +5V through a jumper, or some sort of circuit protection circuit. potentially. 
2. there were near missies with papa and pin alloction, did we check that all the pins allotted can perform the function required? 
3. oh my god if this board is grandppa,,, and papa was named Adam, cannnn we name this one Kyle? 
4. BD9E302EFJ: so from what i'm reading, our inductor value is higher than the one in the dtasheet bc okay im reading more this guy is operating assuming that you put a filter on the output so there is a consistent current draw from the load. Can the battery take 0.6A of fluctiation in input current, and will that fluctuation cause feedback issues in the regulator, will it end up being unstable? from datasheet: "The DC/DC converter **requires** an LC filter for smoothing the output voltage in order to supply a continuous current to the load" I'm concerned about why they said it was required - if its absolutely necessary for the function of the device or it's "required" for optimal operation. 
5. BD9E302EFJ: we are using much higher resistor values for feedbck than these guys have in their application circuit, is this going to cause any issues (ie smaller current draw from FB pin causing change in in voltage at resistor divider) 
6. i think there might be other issues with the BD9E302EFJ, will circle back to it I wanna get through everythign before i get distracted and dont finish this review
7. god bless the little calcualtiosn spreadsheet i love this thing we should make it standard

8. UHHHH the MCP1642B-50I/MS is technically rated to VIN +6.5V, but i don't think its supposed to be operating past vin = 3.3V. I'm not sure how well this component will work at 4.5V

**Comment by Joe-Joe-Joe-Joe** [comment]
1. I am not clear what you are saying. Why would we need a jumper if the issue was with being connected? Couldn't we just... disconnect the 5V supply on the test harness?
2. Volt sense/curr sense is good since all pins have ADC capability. CLK_OUT I'm assuming we can map to another pin as we did with papa. Everything else is GPIO
3. Sure
4. Hardware design 101 is "copy the application circuit". If they say required, its getting an LC filter imo. We should discuss further.
5. Datasheet specifies R1+R2 must be < 700kΩ. Dunno why they chose lower in the application circuit, but if it comes down to it we can always put smaller resistors
6.
7. <3
8. Edit: I don't know my own ICs. Yeah that's a fair point - I'd like to discuss further also.

**Comment by rdakhil** [comment]
1. Yeah we can add some 0 ohms to the harwin power, wouldn’t hurt. Might also help us with debugging 
8. Where do you see the 3.3V max Vin? I see the datasheet referring to Vin > 3.6V. I can put it in simulation and see what happens but it should be fine at 4.5V.

**Comment by rdakhil** [comment]
We can also add 0 ohms to the signals on PIC18 so they can potentially be remapped if there are concerns. This practice is commonly done. Might be overkill though. I’ll triple check the connections before we order the board

**Comment by Rio6** [comment]
2022-12-08-195931_1446x706_scrot
Label not connected to trace?

**Comment by Joe-Joe-Joe-Joe** [comment]
That is very interesting. The trace seems to be routed fine (pin 6 knows what net it should be on), the schematic DRC doesn't flag the pin as unconnected. I will fix but I'm curious if its a graphical glitch?
image
image

**Review by BluCodeGH — APPROVED** [review]
Awesome work y'all, this looks great. There are a bunch of nits below but looking awesome. I'll also point out that you could probably make this board a lot smaller if you wanted to and that right now there's no wiring cutout like papa board had, but as long as that's fine mechanically we're all good.

1. You should probably up the polyfuse (F1, F2, F3) footprints to something like 1812, I don't see many 0805 options on digikey.
2. Part number for TH1?
3. 500 mA (PROG1 resistor) is decently fast for a small lipo. If we're mostly concerned with keeping it topped up / charging overnight I'd drop it down to 100 mA to be safe.
4. R29 is recommended to be 10k on page 20 of the datasheet
5. I think your thermistor math is wrong, I see that it would trip overtemperature at 22.3 kOhm which is like 7 C according to https://www.lasercalculator.com/ntc-thermistor-calculator/ (although it depends on the B value of the thermistor which isn't specified)
6. Isn't standard lipo voltage 4.2V?
7. I'd swap the "Pin 26" silkcreen for "RB5"
8. Nit but unnecessary double vias next to J3.
9. Pin 3 of U6 has traces doubled up to it?

**Comment by rdakhil** [comment]
Yeah it def could be smaller, we just chose to keep it the same size as papa board. we put the connectors on the correct side of the PCB to where the wires will be going so that we wouldn't need cutouts, but we should triple check this with whoever is designing the cubesat before ordering the board

1. Fixed, thanks for checking
2. It's on the schematic already but I'll put it above the thermistor ref des
3. Fixed
4. Fixed
5. Beta value is specified as 3940K on schematic, and Joe has put a calcualtion sheet from the manufacturer in the GitHub folder. I just double checked the math and it checks out. At 55C the thermistor is at 2988 ohms, plus the series resistor gives 5488 ohms, which turns out to 0.2744V, so pretty close to the 0.25V threshold accounting for tolerances. With ideal components the overtemp is at 60 C which is ok imo. I think the 22.3k ohm value (1.24V threshold) is for under temp (or PTCs? idk) which with our thermistor is 10.3 deg C. Good to keep in mind if we decide to test outside during the winter, so thanks for doing the math and pointing that out
6. not sure, i've seen some with max V of 4.2V. We should def choose and buy our lipos soon. Thankfully this battery charge IC has a 4.1V alternative that is pin compatible and in stock rn if we need to change that
7. fixed
8. yeah it looks a bit strange but it's for the CAN differential pairs, L and H have to swap places so it seems this is the only way to do it without daisy-chaining through the connector
9. oh whoops, fixed ty

**Pull request merged**
